# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-27 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('thumbnail', models.FileField(upload_to='')),
                ('body', models.CharField(max_length=5000)),
            ],
        ),
    ]
